before_install:
  - npm install -g @vue/cli

language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: build_demo
      script: "vue create --preset . preset-demo --bare && cd preset-demo && npm run build"